---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cookiemonster-cm-killpod
  namespace: cookiemonster
  labels:
    component: cookiemonster
data:
  openstack-random-daemonset.json: |-
    {
      "name": "",
      "kind": "daemonset",
      "namespace": "openstack",
      "target": 1,
      "interval": 60,
      "duration": 600,
      "slack": true
    }
  openstack-random-deployment.json: |-
    {
      "name": "",
      "kind": "deployment",
      "namespace": "openstack",
      "target": 1,
      "interval": 30,
      "duration": 600,
      "slack": false
    }
  openstack-random-statefulset.json: |-
    {
      "name": "",
      "kind": "statefulset",
      "namespace": "openstack",
      "target": 1,
      "interval": 60,
      "duration": 600,
      "slack": true
    }
