namespace:
  - name: openstack
    resource:
    - kind: deployment
      name:
      target: 1
    - kind: daemonset
      name:
      target: 1
    - kind: statefulset
      name: mariadb
      target: 1
    - kind: statefulset
      name: rabbitmq
      target: 1
interval: 60
duration: 600
slack: true
